# Generated by Django 3.2.5 on 2021-07-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salestodjango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testng',
            name='Email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='testng',
            name='Name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
