# Generated by Django 3.2.5 on 2021-07-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salestodjango', '0002_auto_20210724_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountNumber', models.CharField(max_length=255, null=True)),
                ('LastActivityDate', models.DateField(null=True)),
                ('AnnualRevenue', models.CharField(max_length=255, null=True)),
                ('Name', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'Account',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, null=True)),
                ('Email', models.CharField(max_length=200, null=True)),
                ('AccountID', models.CharField(max_length=255, null=True)),
                ('Phone', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='SfUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=255, null=True)),
                ('FirstName', models.CharField(max_length=255, null=True)),
                ('LastName', models.CharField(max_length=255, null=True)),
                ('Email', models.CharField(max_length=200, null=True)),
                ('LastLoginDate', models.DateField(null=True)),
            ],
            options={
                'db_table': 'SfUser',
            },
        ),
    ]
